spring:
   http:
      multipart:
         maxFileSize: 200MB
         maxRequestSize: 200MB
   mvc:
      view:
         prefix: /WEB-INF/jsp/
         suffix: .jsp
   datasource:
      driverClassName: com.mysql.jdbc.Driver
      url: jdbc:mysql://localhost:3306/springbootxzj?useUnicode=true&characterEncoding=UTF-8&autoReconnect=true
      username: root
      password: 123456
      type: com.alibaba.druid.pool.DruidDataSource
   jpa:
      hibernate:
         ddl-auto: update
      show-sql: true
   cache:
      ehcache:
         cofnig: ehcache.xml
   redis:
      pool:
         max-idle: 10
         min-idle: 5
         max-total: 20
      hostName: 127.0.0.1
      port: 6379
      
mybatis:
   type-aliases-package: com.geekshow.pojo
   
server:
   port: ${random.int[1024,9999]}

hello: geekshow

num: ${random.int}

msg: Hello World ${hello} ${num}